### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by 2128** [gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5#1]
IdentifierAddition.m
line 57 as follows:
http://www.4freeimagehost.com/show.php?i=aed290c4f532.png

**Comment by gekitz** [comment]
This code should work fine. Do you have any special compiler settings enabled?
Otherwise a simple cast from (void *) to (char *) will solve the problem.

**Comment by Ricardo1980** [comment]
To share a code snipped easily you can use https://gist.github.com/ although I don't know if there is a way to mark a compiler error.

**Comment by gekitz** [comment]
I don't think you can mark compiler errors there ;) It's a simple pasteboard with code highlighting.
