### ISSUE TITLE
Add a version tag

### ISSUE THREAD

**Issue by mmassaki** [gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5#10]
Please, could you add a version tag?

I need this to create a cocoapods podspec to this library.

Thanks

**Comment by gekitz** [comment]
just created a version tag.

Cheers,
Georg

**Comment by mmassaki** [comment]
Thanks!
I have already added UIDeviceAddition to CocoaPods Specs.

**Comment by gekitz** [comment]
Nice ;)
