### ISSUE TITLE
Enhance Readme

### ISSUE THREAD

**Issue by thorst** [gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5#12]
Would be nice if the readme contained:
1. http://stackoverflow.com/questions/9897162/ios-uuid-generation-throwing-a-strange-exception <- The instructions to make sure both m files are compiled.
2. Im using arc so at the above screen i also had to add "-fno-objc-arc" as a compiler flag
3. add "#import "UIDevice+IdentifierAddition.h"" to the top of the .m file
4.Better clarification as to the difference between global and regular. Im guessing the regular is app specific so an uninstall reinstall will give you a different number. Whereas global will be the same across reinstalls.

Just a suggestion. If you dont want to do it i can do a pull (i think thats what its called, still new to github)

**Comment by gekitz** [comment]
Sounds good, I will  improve the readme asap. Just some thoughts on the points you mentioned.
1. I think we don't need this
2. Makes sense, I will also convert it to ARC as soon as possible.
3. It's not necessary to add it on the top of the .m file. Why do you think this is necessary?
4. Makes sense, people always ask what the difference is and yes it's my fault that I haven't explained it clear enough.
