### ISSUE TITLE
How long do you think this will work?

### ISSUE THREAD

**Issue by rodrigozanatta** [gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5#2]
OK, The apple don't want their devices have unique identifiers. But, you create exactly what apple don't want!

So.. Apple failed to achieve his goal. And now, what it can do against your program? Is easy to him detect this this codes and reject programs with it? You know program that was rejected because this?

What do you think?

**Comment by gekitz** [comment]
Yes I created smth Apple don't want, but I need this feature in some of my Apps. 
I use some parts of this code in Apps which are in App Store at the moment. 

From my point of view, the source code should be no problem, but yes, we are working against Apple guidelines.
