### ISSUE TITLE
iOS 7 users receiving the same UDID

### ISSUE THREAD

**Issue by nothingimportant55** [gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5#21]
My users have just started upgrading to the iOS 7 beta, and I'm finding that their UDIDs have changed and hundreds of them are being assigned the same UDIDs as each other.

**Comment by fresswolf** [comment]
I guess Apple now blocks access to the MAC address

**Comment by rapher** [comment]
@gekitz will you make this submodule work with iOS7?

**Comment by gekitz** [comment]
@rapher no, there is no way to make it work under iOS 7 as the MAC address access works differently under iOS 7.
