### ISSUE TITLE
Get Same Device ID String

### ISSUE THREAD

**Issue by aozhimin** [gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5#24]
I got Same Device ID String in my different device, one is ios7.0.4, one is ios8.3, Why?

**Comment by deepaksahu-mob-ibtech** [comment]
I got same issue with iOS version 7.x and above.
iOS 7 and above versions devices – are always returning a MAC address of 02:00:00:00:00:00

**Comment by solaadio** [comment]
It no longer works on iOS7 and above

**Comment by aozhimin** [comment]
ok, got it
