### ISSUE TITLE
How unique is uniqueGlobalDeviceIdentifier?

### ISSUE THREAD

**Issue by samvermette** [gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5#6]
I have a database of users which are identified by their udid and I'm now transitioning to your `uniqueGlobalDeviceIdentifier`. I'm wondering, is it possible that one of these new identifier ends up being the same as an old udid (but belonging to a different user)?

The udid used to be `SHA1(SerialNumber + IMEI + WiFiAddress + BluetoothAddress)`, whereas this new identifier is `MD5(MAC address)`. I'm not too familiar with how SHA1 and MD5 work, but is it a possibility that, even though all the variables are different, the end result ends up being the same, since they are encrypted using different algorithms?

**Comment by gekitz** [comment]
Yes that could be possible.

**Comment by kris1090** [comment]
Hi, We are planning to use this to generate unique device ids. We have multiple apps and we want all of the apps to have same device id when running on same device.
It is very important that all devices have separate device ids. Can you please confirm that every device will really get a unique device id?

**Comment by kris1090** [comment]
Any update?
