### ISSUE TITLE
Crashes for Distribution builds

### ISSUE THREAD

**Issue by appit** [gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5#7]
This works ok in a dev build, but as soon as you build for a distribution it will crash.

**Comment by meachware** [comment]
I'm using it in a couple of apps already deployed and available through the store. Pretty sure you need to double check your project, or something. Post the actual error in the console log :-)

**Comment by gekitz** [comment]
Sounds weird. The code should work in a distribution build as well. I'm with meachware, please double check your code. I will close this issue.
