### ISSUE TITLE
Actually viable in the App Store?

### ISSUE THREAD

**Issue by msmollin** [gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5#8]
I see this is utilizing LLADDR, a BSD networking tool, to grab the mac address. Has anyone that you know of run this through Apple's private framework checks & review process to make sure it's OK to be using it?

**Comment by gekitz** [comment]
As far as I can tell, it's App Store save. I use it in one of my Apps and I had no problems with Apple's review process.
