### ISSUE TITLE
Remove uniqueIdentifier method

### ISSUE THREAD

**Issue by coneybeare** [gekitz/UIDevice-with-UniqueIdentifier-for-iOS-5#9]
Apple is [now rejecting](http://maniacdev.com/2012/03/apps-using-udids-being-rejected-by-apple-heres-how-to-generate-replacements-quickly) apps that call it. It should be removed from the code.

**Comment by gekitz** [comment]
I know they are rejecting apps which call uniqueIdentifier, but that's not what the open source thing does. We don't call this method we call a replacement. Either unique_Device_Identifier or unique_GlobalDevice_Identifier. I haven't heard from someone that Apple is rejecting this as well. Have you?

**Comment by coneybeare** [comment]
My bad. I was looking for this repo: https://github.com/ylechelle/OpenUDID

**Comment by gekitz** [comment]
hehe okay, so I will close this issue ;)
